In [15]:
## This block will contain testing of numoy arrays, and how to concatenate these effectively
import numpy as np
small_array = np.array([1,2,3])
print(type(small_array))
print(small_array)
#np.append(small_array,small_array,axis=0)
stacked_array = np.vstack((small_array,small_array))
print(type(stacked_array))
print(stacked_array)

## It seems that using np.vstack is useful for this 

<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]]
